### ISSUE TITLE
Discuss how ranking system could be implemented

### ISSUE THREAD

**Issue by Yuno-obsessed** [Yuno-obsessed/shikimori#1]
- [1] Where can data be stored :fire: 
- [2] How can rank level up :fire: 
- [3] How to show users when they rank is leveled up :fire:

**Comment by 4cecoder** [comment]
[3] How to level up?
Well... What exactly do you want to encourage using a ranking system??
What do you want to be more interactive(gamified)?

Usually in discord servers the Leveling/Ranking system would be to "gameify" keeping the chat active
If you choose this route:
 	this would mean each message each day you could get a certain amount of points towards your rank.

**Comment by Yuno-obsessed** [comment]
For now my intention is to let discord server admins decide how the ranking system will work on their server. For now I came up with some ideas of possible options:
- To give "rank points" to server members for writing messages;
- To add commands which can be executed by members with some roles to "add" and "subtract" certain quantity of "rank points";

**Comment by Yuno-obsessed** [comment]
Talking about what roles will serve for:
-  Just for fun, to have levels up to 100 and certain quantity needed to reach each of them;
-  To give roles for some actions (contributing to discord community in this server, uploading useful information(such as links, images, posts) and some other stuff) (Suits better for second option of ranking systems and in my opinion is better for discord communities that are gathered around some general topic (maintainers or contributors of a github projecs and so on);
